ccflags-y += -Idrivers/media/platform/msm/camera_v2_piccolo
ccflags-y += -Idrivers/media/platform/msm/camera_v2_piccolo/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_piccolo/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
