ccflags-y += -Idrivers/media/platform/msm/camera_v2_piccolo
ccflags-y += -Idrivers/media/platform/msm/camera_v2_piccolo/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_piccolo/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
